import {
  Menu as MenuIcon,
  Close as CloseIcon,
  Home as HomeIcon,
  CreditCard as CreditCardIcon,
  People as PeopleIcon,
  Settings as SettingsIcon,
  BarChart as BarChartIcon,
  Description as DescriptionIcon,
  Notifications as NotificationsIcon,
  Logout as LogoutIcon,
  TrendingUp as TrendingUpIcon,
  AttachMoney as AttachMoneyIcon,
  ShoppingCart as ShoppingCartIcon,
  Timeline as TimelineIcon,
  Search as SearchIcon,
  Add as AddIcon,
  Visibility as VisibilityIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  ContentCopy as ContentCopyIcon,
  Download as DownloadIcon,
  Send as SendIcon,
  FilterList as FilterListIcon,
  Person as PersonIcon,
  Business as BusinessIcon,
  Phone as PhoneIcon,
  Email as EmailIcon,
  LocationOn as LocationOnIcon,
  CalendarToday as CalendarTodayIcon,
  Receipt as ReceiptIcon,
  Payment as PaymentIcon,
  LocalShipping as LocalShippingIcon,
  Info as InfoIcon,
  Warning as WarningIcon,
  Error as ErrorIcon,
  CheckCircle as CheckCircleIcon
} from '@mui/icons-material';

// Map Lucide icon names to Material-UI components
export const iconMap = {
  Menu: MenuIcon,
  X: CloseIcon,
  Home: HomeIcon,
  CreditCard: CreditCardIcon,
  Users: PeopleIcon,
  Settings: SettingsIcon,
  BarChart3: BarChartIcon,
  FileText: DescriptionIcon,
  Bell: NotificationsIcon,
  LogOut: LogoutIcon,
  TrendingUp: TrendingUpIcon,
  DollarSign: AttachMoneyIcon,
  ShoppingCart: ShoppingCartIcon,
  Activity: TimelineIcon,
  Search: SearchIcon,
  Plus: AddIcon,
  Eye: VisibilityIcon,
  Edit2: EditIcon,
  Trash2: DeleteIcon,
  Copy: ContentCopyIcon,
  Download: DownloadIcon,
  Send: SendIcon,
  Filter: FilterListIcon,
  User: PersonIcon,
  Building: BusinessIcon,
  Phone: PhoneIcon,
  Mail: EmailIcon,
  MapPin: LocationOnIcon,
  Calendar: CalendarTodayIcon,
  File: ReceiptIcon,
  CreditCard: PaymentIcon,
  Truck: LocalShippingIcon,
  Info: InfoIcon,
  AlertTriangle: WarningIcon,
  AlertCircle: ErrorIcon,
  CheckCircle: CheckCircleIcon
};

// Helper function to get Material-UI icon component
export const getIcon = (name, props = {}) => {
  const IconComponent = iconMap[name];
  return IconComponent ? <IconComponent {...props} /> : null;
}; 